---
- name: 
  hosts: ubuntu01-dev
  become: true
  tasks:
  - name: Install apache2 server
    apt: 
      name: apache2
      update_cache: yes
      state: present
  - name: Copy index.html to dev-server
    copy:
      src: /tmp/index.html
      dest: /var/www/html/index.html
  - name: Start apache2
    service:
      name: apache2
      state: started
  - name: Enable apache2
    service:
      name: apache2
      enabled: yes
