---
# tasks file for install_nginx

- name: Install nginx
  yum:
    name: nginx
    state: latest
- name: save original nginx.conf to nginx.conf.org
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
- name: Copy nginx files
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Restart Nginx
